- hosts: master
  name: Run `kubeadm init` on master nodes
  become: True
  gather_facts: False
  tags:
    - kubeadm-init
  tasks:
    - name: Upload `kubeadm init` config file
      template:
        src: templates/kubeadm.config.j2
        dest: /root/kubeadm.config
    - name: Run `kubeadm init`
      command: kubeadm init --config /root/kubeadm.config
      args:
        creates: /etc/kubernetes/admin.conf
      register: kubeadm_init_out
    - name: Create `kubeadm join` script for worker nodes
      copy:
        content: |
          #!/bin/bash
          {{ kubeadm_init_out.stdout_lines[-2] }}
          {{ kubeadm_init_out.stdout_lines[-1] }}
        dest: "/root/join.sh"
    - name: Delete `kubeadm init` config file
      file:
        state: absent
        path: /root/kubeadm.config

- hosts: master
  name: Download kubeconfig files from master nodes
  become: True
  gather_facts: False
  tags:
    - download-kubeconfig
  vars:
    public_ip: "{{ hostvars[inventory_hostname].ansible_host }}"
    kubeconfig: "{{ inventory_hostname }}.conf"
  tasks:
    - name: Prepare local kubeconfig file
      shell: |
        cp /etc/kubernetes/admin.conf /root/{{ kubeconfig }}
        kubectl --kubeconfig /root/{{ kubeconfig }} config set-cluster kubernetes --server https://{{ public_ip }}:6443
    - name: Ensure localhost directory for kubeconfig files
      become: False
      local_action:
        module: file
        path: ../kubeconfig
        state: directory
    - name: Download local kubeconfig file
      fetch:
        src: /root/{{ kubeconfig }}
        dest: ../kubeconfig/
        flat: yes
    - name: Delete local kubeconfig file
      file:
        state: absent
        path: /root/{{ kubeconfig }}
