- hosts: worker
  name: Join cluster
  become: True
  gather_facts: False
  tasks:
    - name: Create temporary file on localhost
      become: False
      local_action: tempfile
      register: tmp
    - name: Download `kubeadm join` script from master node to temporary file
      delegate_to: "{{ master }}"
      fetch:
        src: /root/join.sh
        dest: "{{ tmp.path }}"
        flat: yes
    - name: Upload `kubeadm join` script to worker node
      copy:
        src: "{{ tmp.path }}"
        dest: /root/join.sh
        mode: +x
    - name: Run `kubeadm join` script on worker node
      command: /root/join.sh
      args:
        creates: /etc/kubernetes/kubelet.conf
    - name: Delete `kubeadm join` script on worker node
      file:
        state: absent
        path: /root/join.sh
