- hosts: worker
  name: Run `kubeadm reset` on worker nodes
  become: True
  gather_facts: False
  tags:
    - reset-workers
  tasks:
    - name: Run `kubeadm reset`
      command: kubeadm reset -f
      args:
        removes: /etc/kubernetes/kubelet.conf

- hosts: master
  name: Run `kubeadm reset` on master nodes
  become: True
  gather_facts: False
  tags:
    - reset-masters
  tasks:
    - name: Run `kubeadm reset`
      command: kubeadm reset -f
      args:
        removes: /etc/kubernetes/admin.conf

- hosts: localhost
  name: Delete the local `kubeconfig` directory
  become: False
  gather_facts: False
  tags:
    - delete-kubeconfig
  tasks:
    - name: Delete `kubeconfig` directory
      file:
        path: ../kubeconfig
        state: absent
